import catalogData from './catalog-data.json';

export type Category = {
    name: string;
    imageCount: number;
    previewImage: string | null;
    slug: string;
    metadata?: FolderMetadata;
};

export type Variant = {
    label: string;
    price?: number;
    compareAtPrice?: number;
};

export type FolderMetadata = {
    originalPrice?: number;
    salePrice?: number;
    isOffer?: boolean;
    isFreeShipping?: boolean;
    material?: string;
    variants?: Variant[];
};

export type ContentItem = {
    type: 'category' | 'image';
    name: string;
    src?: string; // for images
    slug?: string; // for categories
    count?: number; // for categories
    preview?: string | null; // for categories
    metadata?: FolderMetadata;
};

export type DirectoryContent = {
    name: string;
    subcategories: ContentItem[];
    images: ContentItem[];
    metadata?: FolderMetadata;
};

export async function getCategories(): Promise<Category[]> {
    // We return the precomputed categories from the JSON payload.
    // The structure generated by our pre-build script matches Category[] directly.
    return catalogData.categories as Category[];
}

export async function getDirectoryContent(slugs: string[]): Promise<DirectoryContent | null> {
    const slugKey = slugs.map(s => decodeURIComponent(s)).join('/');

    // Fallback/validation if attempting directory traversal (though shouldn't happen with Next router)
    if (slugKey.includes('..')) return null;

    // Use a loose type for the map to appease TS about the lookup
    const contentsMap: Record<string, DirectoryContent> = catalogData.contents as Record<string, DirectoryContent>;
    const content = contentsMap[slugKey];

    if (!content) return null;

    return content;
}
